name: scanntech-challenge-env
channels:
  - default
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.3
  - ipython=8.12.0
  - jupyter=1.0.0
  - jupyterlab=3.6.3
  - jupyter_contrib_nbextensions
  - numpy=1.24.3
  - pandas=1.5.3
  - plotly=5.9.0
  - statsmodels=0.14.0
  - pip=23.2.1
  - pip:
    - scikit-learn==1.3.0
